function createConfig(filepath)
% createConfig(filepath)
% inputs  - filepath, the directory to create the file path in.
% Remarks
% - This function creates an initial configuration file for the BAR App. It can also be used outside the app.
% - Many of the data are initialized as empty or blank objects. These will need to be set within the app and will then be remembered when run the next
% time.
% Future Work
% - As some of the method choices in the app are made more dynamic these options will need to change.
% Nov 2022 - Created by Ben Senderling, bsender@bu.edu

% Create the structure that will be the conf file.
config = struct;

% Create empty arrays for the working directory and the search directories.
config.directory = '';
config.database = '';

% Create empty arrays the various method directories.
config.options.filesload = '';
config.options.filesprocess = '';
config.options.filesanalysis = '';
config.options.filesreview = '';

% Create an empty array for the file types.
config.options.filetypes = [];

% Available treatment modules.
% config.treatment = {...
%    'General Treatment', 'process_Treatment',...
%    'Segment', 'process_Segment'};
config.treatment_general = {...
    'Low-pass Filter', 'process_Treatment_LowPass',...
    'Resample', 'process_Treatment_Resample'};
% config.segmentation_general = {...
%     'Threshold', 'process_Segment_Threshold',...
%     'Turning in IMUs', 'process_Segment_IMUTurns',...
%     'WESENS Opal 3', 'process_Segment_WESENSOpal3'};

% Available analysis modules.
% config.analysis = {...
%     'Time Lag', 'analysis_TimeLag',...
%     'FNN', 'analysis_FNN',...
%     'RQA', 'analysis_RQA'};

% Available review modules.
% config.review = {...
%     'Raw Data', 'review_RAW',...
%     'Time Lag', 'review_TimeLag',...
%     'FNN', 'review_FNN',...
%     'RQA', 'review_RQA'};

% config.figures = {...
%     '1D', '',...
%     '2D', '',...
%    '3D', '',...
%    'MD', 'figure_MD',...
%    'Image', ''};

% Available export modules.
config.export = {...
    'General',...
    'BU Caltesting',...
    'Tables'};

% Write the config file to an xml file.
writestruct(config, [filepath '\config.xml'])