function createConfig(filepath)

% Create the structure that will be the conf file.
config = struct;

% Creates an empty directory to search for files. This will be remembered
% after running the app the first time.
config.directory = '';

% Creates an empty directory to specify the database. This will be
% remembered after running the app the first time. When a folder is
% selected the app will check that all the needed subfolders are present
% and if they aren't, create them.
config.database = '';

% This was the previous method of assigning load functions to file types 
% and specific equipment formats. It was replaced with the Configuration
% window in the app and the lines of code further below.
% config.options.files.h5 = 'APDM';
% config.options.files.txt = 'V3D';
% config.options.files.mat = 'BAR';
% config.options.files.xls = 'XLSX';
% config.options.files.png = 'Windows';

config.options.filesload = 'C:\Users\bsender\OneDrive - Boston University\BU\Projects\001 BAR\Code\BAR_App\Load';
config.options.filetypes = [];
config.options.filesprocess = 'C:\Users\bsender\OneDrive - Boston University\BU\Projects\001 BAR\Code\BAR_App\Process';
config.options.filesanalysis = 'C:\Users\bsender\OneDrive - Boston University\BU\Projects\001 BAR\Code\BAR_App\Analysis';

% Available treatment modules.
config.treatment = {...
    'General Treatment', 'process_Treatment',...
    'Segment', 'process_Segment'};
config.treatment_general = {...
    'Low-pass Filter', 'process_Treatment_LowPass',...
    'Resample', 'process_Treatment_Resample'};
config.segmentation_general = {...
    'Threshold', 'process_Segment_Threshold',...
    'Turning in IMUs', 'process_Segment_IMUTurns',...
    'WESENS Opal 3', 'process_Segment_WESENSOpal3'};

% Available analysis modules.
config.analysis = {...
    'Time Lag', 'analysis_TimeLag',...
    'FNN', 'analysis_FNN',...
    'RQA', 'analysis_RQA'};

% Available review modules.
config.review = {...
    'Raw Data', 'review_RAW',...
    'Time Lag', 'review_TimeLag',...
    'FNN', 'review_FNN',...
    'RQA', 'review_RQA'};

config.figures = {...
    '1D', '',...
    '2D', '',...
    '3D', '',...
    'MD', 'figure_MD',...
    'Image', ''};

% Available export modules.
config.export = {...
    'General',...
    'BU Caltesting'};

% Write the config file to an xml file.
writestruct(config, [filepath '\config.xml'])