function createConfig(filepath)
% createConfig(filepath)
% inputs  - filepath, the directory to create the file path in.
% Remarks
% - This function creates an initial configuration file for the BAR App. It can also be used outside the app.
% - Many of the data are initialized as empty or blank objects. These will need to be set within the app and will then be remembered when run the next
% time.
% Future Work
% - As some of the method choices in the app are made more dynamic these options will need to change.
% Nov 2022 - Created by Ben Senderling, bsender@bu.edu
% Dec 2022 - Modified by Ben Senderling, bsender@bu.edu
%          - Made a number of the fields dynamically created by the app so here they only need to be initiallized.
% Jan 2023 - Modified by Ben Senderling, bsender@bu.edu
%          - Added a field point to the location of this configuration file.

% Create the structure that will be the conf file.
config = struct;

config.configuration = [filepath '\config.xml'];

% Create empty arrays for the working directory and the search directories.
config.directory = '';
config.database = '';

% Create empty arrays the various method directories.
config.options.filesload = '';
config.options.filesprocess = '';
config.options.filesanalysis = '';
config.options.filesreview = '';

% Create an empty array for the file types.
config.options.filetypes.AllFiles = {'AllFiles'};
config.options.filetypes.agd = {'Actigraph'};
config.options.filetypes.csv = {'Axivity', 'BertecCDP', 'DAMVi', 'Delsys', 'NHATSAcceleration', 'Actigraph', 'Basic'};
config.options.filetypes.gt3x = {'Actigraph'};
config.options.filetypes.h5 = {'APDM0Meta', 'APDM1Raw', 'APDM2Results', 'APDM3Qua', };
config.options.filetypes.m = {'MATLAB'};
config.options.filetypes.mat = {'DAMVi', 'OpenCap', 'QTM'};
config.options.filetypes.mlapp = {'MATLAB'};
config.options.filetypes.mot = {'OpenSim'};
config.options.filetypes.png = {'WIN'};
config.options.filetypes.qtm = {'QTM'};
config.options.filetypes.txt = {'V3D'};
config.options.filetypes.xlsx = {'Medoc'};

% Available processing modules.
config.options.process = {...
    'APDM',...
    'Eventing',...
    'Segment',...
    'Treatment'...
    };

% Available treatment modules.
 config.options.treatment = {...
    'Add signals',...
    'Low-pass filter',...
    'Resample',...
    'Residual analysis'...
    };

% config.segmentation_general = {...
%     'Threshold', 'process_Segment_Threshold',...
%     'Turning in IMUs', 'process_Segment_IMUTurns',...
%     'WESENS Opal 3', 'process_Segment_WESENSOpal3'};

% Available analysis modules.
config.options.analysis = {...
    'Actigraph',...
    'ContinuousSignalMetrics', 'COP', 'CorrelationDimension', 'CrossSignalMetrics',...
    'Delsys', 'DFA',...
    'Entropy',...
    'FNN',...
    'LyE',...
    'RQA',...
    };

% Available review modules.
config.options.review = {...
    'General', 'QC',...
    };

% Available figure types.
config.options.figure = {...
    '1D', '2D', '3D',...
    'TimeLag', 'FNN', 'RQA'...
    'Histogram',...
    'Image'};

% Available export modules.
config.export = {...
    'General',...
    'BU Caltesting',...
    'Tables'};

% Write the config file to an xml file.
writestruct(config, [filepath '\config.xml'])